files:
  - source: '**/config/locales/en.yml'
    translation: /config/locales/%two_letters_code%.yml
    languages_mapping:
      two_letters_code:
        sv-SE: sv-SE
        zh-CN: zh-CN
        zh-TW: zh-TW
        pt-PT: pt
        pt-BR: pt-BR
        es-ES: es-ES
        es-MX: es-MX
